### ISSUE TITLE
Minor enhancements for the README file

### ISSUE THREAD

**Issue by leferrad** [agusmdev/fastapi-ddd-template#4]
Here is a list of minimal corrections for better understanding (take it or leave it):
- `100% test coverage included` -> `100% code coverage in included tests` 
- `Poetry used for package management, simplifying dependency management.` ->  `Poetry used for dependency management` 
- `Pydantic Factories for easy test mocking.` ->  `Pydantic Factories for easy mocking in tests`

**Comment by agusmdev** [comment]
Great! Added those suggestions
