### ISSUE TITLE
Handling Python version

### ISSUE THREAD

**Issue by leferrad** [agusmdev/fastapi-ddd-template#7]
In the install script: https://github.com/agusmdev/fastapi-ddd-template/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/scripts/install.sh#L9

the Python version is forced to 3. Maybe the user wants to select the Python version (even which specific version), or at least let the user know that this only works with Python 3.

**Comment by agusmdev** [comment]
Nice catch, added requirement of python3.8 to the readme
